#
# CustomSprays by LSDog
#
# 权限 | Permissions:
#   请自行查看 jar(插件文件) 内的 plugin.yml
#   Go check plugin.yml in plugin jar file
#
#

debug: true
# Debug 会输出所有玩家上传的图片链接和文件大小
# Debug Out put image link and file size
# 默认|Default: true

custom_prefix: "§6CustomSprays >>§r "
# 插件发送消息的前缀
# Message prefix by plugin
# 默认|Default: "§6CustomSprays >>§r "

destroy: 40
# 玩家喷漆自动消失时间 (秒)
# Spray self destroy time (Second)
# 默认|Default: 40

distance: 3
# 玩家喷漆到方块的最大距离 (格)
# Biggest distance from player to block (Block)
# 默认|Default: 3

spray_cooldown: 30
# 玩家喷漆和获取预览图的时间间隔 (秒)
# Cool down between player spray or get map for a view (Second)
# 默认|Default: 30

upload_cooldown: 60
# 玩家上传图片的时间间隔 (秒)
# Cool down between player upload a new image (Second)
# 默认|Default: 60

file_size_limit: 256
# 玩家提供的图片大小限制 (kb)
# Max size of the spray image (kb)
# 默认|Default: 256

use_MySQL: false
# true -> 使用 MySQL存储 | false -> 使用 yml 存储
# Use MySQL if true, otherwise save to imageData.yml
# 默认|Default: false

# 支持 MySQL 其他的数据库没有试过, SQLite 貌似是可行的
# Support MySQL, maybe SQLite is OK ... haven't try that
MySQL:
  host: '127.0.0.1'
  port: '1433'
  database: 'minecraft'
  user: 'root'
  password: 'password'


Messages:
  INPROGRESS: