name: CustomSprays
version: 1.0
main: fun.LSDog.CustomSprays.CustomSprays
authors: [LSDog]

commands:
  customsprays:
    aliases: [sprays]
    description: 插件主命令
  spray:
    description: 喷喷漆

permissions:
  CustomSprays.spray:
    default: true
    description: 允许喷漆 | allow spray
  CustomSprays.viewself:
    default: true
    description: 允许查看自己上传的图像 | can get a map from self (/customsprays view)
  CustomSprays.viewothers:
    default: op
    description: 允许查看其他玩家的图像 | can get a map from any player (/customsprays view <player>)
  CustomSprays.nocooldown:
    default: op
    description: 没有上传，喷涂和查看的冷却 | no cooling for spray, upload and view