name: CustomSprays
version: 1.2
main: fun.LSDog.CustomSprays.CustomSprays
authors: [LSDog]
softdepend: [PlaceholderAPI]

commands:
  customsprays:
    aliases: [cspray]
    description: 插件主命令
  spray:
    description: 喷喷漆

permissions:
  CustomSprays.spray:
    default: true
    description: 允许喷漆 | Allow spray
  CustomSprays.view:
    default: op
    description: 允许查看其他玩家的图像 | Can get a map from any player (/customsprays view <player>)
  CustomSprays.noCD:
    default: op
    description: 没有上传和喷涂的冷却 | No cooling for spray and upload